programdir:
  dir: "/projects/wp2/nobackup/Twist_Myeloid/Bin/pomfrey/"

reference:
    ref: "/data/ref_genomes/hg19/genome_fasta/hg19.with.mt.fasta"
    bwa: "/data/ref_genomes/hg19/bwa/BWA_0.7.10_refseq/hg19.with.mt.fasta" ##Why two folders should be the same as genome_fasta

configCache:
    multiqc: "/projects/wp2/nobackup/Twist_Myeloid/Bin/pomfrey/src/report/multiqc_config.yaml"
    igv: "/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/caches/igv/genomes/hg19.genome"
    vep: "/data/ref_genomes/VEP/"
    hemato: "/data/ref_data/COSMIC/COSMIC_v90_hemato_counts.txt"
    variantlist: "/projects/wp4/nobackup/workspace/arielle_test/twist/twistVariants.txt"

bed:
    bedfile: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeolid_padd6_200507.bed"
    pindel: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/twist_shortlist_pindel-200423.bed"    #annotated_pindel.bed"
    cartool: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeolid_padd6_200507.bed" #"/projects/wp2/nobackup/Twist_Myeloid/Bed_files/twist_annotated_cartool.bed" #Why different? Should use the same as bedfile?
    hotspot: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Hitlist_Sept2016_final_onePOS.bed"
    artefact: "/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Artefacts_Mars2020.txt"
    germline: "/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Low_VAF_SNVs_March2020.txt"
    intervals: "/projects/wp2/nobackup/Twist_Myeloid/Bed_files/Twist_myeolid_padd6_200507.intervals"

singularitys:
    cutadapt: "/projects/wp2/nobackup/Twist_Myeloid/Containers/cutadaptv2.5-0.simg"
    bwa: "/projects/wp2/nobackup/Twist_Myeloid/Containers/bwa0.7.17-samtools-1.9.simg"
    fastqc: "/projects/wp2/nobackup/Twist_Myeloid/Containers/fastqc0.11.8.simg"
    cartool: "/projects/wp2/nobackup/Twist_Myeloid/Containers/CARTools-200206.simg"
    bcftools: "/projects/wp2/nobackup/Twist_Myeloid/Containers/bcftools-1.9--8.simg"
    freebayes: "/projects/wp2/nobackup/Twist_Myeloid/Containers/freebayes-1.3.1-0.simg"
    lofreq: "/projects/wp2/nobackup/Twist_Myeloid/Containers/lofreq-2.1.3.1-0.simg"
    pisces: "/projects/wp2/nobackup/Twist_Myeloid/Containers/Pisces-5.2.11.simg"
    snver: "/projects/wp2/nobackup/Twist_Myeloid/Containers/snver-0.5.3-0.simg"
    vardict: "/projects/wp2/nobackup/Twist_Myeloid/Containers/vardict-java-1.7.0-0.simg"
    pindel: "/projects/wp2/nobackup/Twist_Myeloid/Containers/pindel-0.2.5b8.simg"
    vep: "/projects/wp2/nobackup/Twist_Myeloid/Containers/ensembl-vep-99.0.simg"
    recall: "/projects/wp4/nobackup/workspace/somatic_dev/singularity/bcbio-variation-recall.simg" #Need one with bcftools and recall
    python: "/projects/wp2/nobackup/Twist_Myeloid/Containers/python3.6.0-pysam-xlsxwriter.simg"
    vt: "/projects/wp2/nobackup/Twist_Myeloid/Containers/vt-0.57721-2.simg"
    igv: "/projects/wp2/nobackup/Twist_Myeloid/Containers/igv-2.4.10-0.simg"
    multiqc: "/projects/wp2/nobackup/Twist_Myeloid/Containers/multiqc-1.7.simg"

cartool:
    cov: "100 200 1000"

methods:   ##Should we have it here or skip and put in snakemake-file
    vardict: "vardict"
    pisces: "pisces"
    freebayes: "freebayes"
    # lofreq: "lofreq"
    snver: "snver" #manta: "manta"

samples:
