programdir:
  dir: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/"

reference:
    ref: "/data/ref_genomes/hg19/genome_fasta/hg19.with.mt.fasta"
    igv: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/caches/igv/genomes/hg19.genome"

configCache:
    multiqc: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/report/multiqc_config.yaml"
    igv: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/caches/igv/genomes/hg19.genome"
    vep: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/caches/vep"

bed:
    bedfile: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/bedfiles/all_targets_covered_by_probes_combined_sorted_merged_ann_padd10.bed"
    pindel: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/bedfiles/twist_shortlist_pindel.bed"    #annotated_pindel.bed"
    cartool: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/bedfiles/all_targets_covered_by_probes_combined_sorted_merged_ann_padd10.bed" #"/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/bedfiles/twist_annotated_cartool.bed" #Why different? Should use the same as bedfile?
    hotspot: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/bedfiles/Hitlist_Sept2016_final_onePOS.bed"
    artefact: "/gluster-storage-volume/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Artefacts_Feb2020.txt"
    germline: "/gluster-storage-volume/projects/wp2/nobackup/Twist_Myeloid/Artefact_files/Low_VAF_SNVs.txt"
    intervals: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/bedfiles/all_targets_covered_by_probes_combined_sorted_merged_ann_padd10.interval"

singularitys:
    cutadapt: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/cutadaptv2.5-0.simg"
    bwa: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/bwa0.7.17-samtools-1.9.simg"
    fastqc: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/fastqc0.11.8.simg"
    cartool: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/CARTools-200206.simg"
    bcftools: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/bcftools-1.9--8.simg"
    freebayes: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/freebayes-1.3.1-0.simg"
    lofreq: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/lofreq-2.1.3.1-0.simg"
    pisces: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/Pisces-5.2.11.simg"
    snver: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/snver-0.5.3-0.simg"
    vardict: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/vardict-java-1.7.0-0.simg"
    pindel: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/pindel-0.2.5b8.simg"
    vep: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/ensembl-vep-99.0.simg"
    recall: "/gluster-storage-volume/projects/wp4/nobackup/workspace/somatic_dev/singularity/bcbio-variation-recall.simg" #Need one with bcftools and recall
    python: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/python3.6.0-pysam-xlsxwriter.simg"
    vt: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/vt-0.57721-2.simg"
    igv: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/igv-2.4.10-0.simg"
    multiqc: "/gluster-storage-volume/projects/wp4/nobackup/workspace/arielle_test/somaticpipeline/src/singularity/multiqc-1.7.simg"

cartool:
    cov: "100 500 1000"

methods:   ##Should we have it here or skip and put in snakemake-file
    vardict: "vardict"
    pisces: "pisces"
    freebayes: "freebayes"
    # lofreq: "lofreq"
    snver: "snver" #manta: "manta"

samples:
